turtlebot3: #namespace

    n_actions: 3 # We have 3 actions, Forwards,TurnLeft,TurnRight
    n_observations: 6 # We have 6 different observations

    speed_step: 1.0 # Time to wait in the reset phases

    linear_forward_speed: 0.45 # Spwwed for ging fowards  原为0.5                                     0.45
    linear_turn_speed: 0.45 # Lienare speed when turning                                             0.45
    angular_speed: 0.9 # Angular speed when turning Left or Right  原为0.3                            0.9
    init_linear_forward_speed: 0.0 # Initial linear speed in which we start each episode
    init_linear_turn_speed: 0.0 # Initial angular speed in shich we start each episode
    
    new_ranges: 51.4285714286 # How many laser readings we jump in each observation reading, the bigger the less laser resolution
    min_range: 0.1 # Minimum meters below wich we consider we have crashed                          0.1
    max_laser_value: 1 # Value considered Ok, no wall
    min_laser_value: 0.11 # Value considered there is an obstacle or crashed                         0.11
    max_linear_aceleration: 5.0 # Linear acceleration value in which we consider Turtlebot 3 has crashed into something
    
    forwards_reward: 1 # Points Given to go forwards
    turn_reward: 0.2 # Points Given to turn as action
    end_episode_points: 10 # Points given when ending an episode
    
    xmin: -5.0
    ymin: -5.0
    xmax: 5.0
    ymax: 5.0
    
    

